# Generated by Django 4.2.6 on 2023-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_rename_lname_student_lname_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
